---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "myaccidentalert"
    version: "1.0.0-SNAPSHOT"
    group: "org.redhat.demo"
  name: "myaccidentalert"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "myaccidentalert"
    provider: "fabric8"
    group: "org.redhat.demo"
