---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "e61d74658e82b4690e114f63f4647e9a5a479eca"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "myclaimdemo"
    version: "1.0.0-SNAPSHOT"
    group: "org.redhat.demo"
  name: "myclaimdemo"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "myclaimdemo"
    provider: "fabric8"
    group: "org.redhat.demo"
